name: Backup
on:
  schedule:
    - cron: "10 15 1-31/2 * *"
#  push:
#    branches:
#      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check and release
        run: |
            rm -fr *
            sudo apt update
            sudo apt install upx git -y
            sudo snap install go --classic
            go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest> /dev/null
            GOOS=linux GOARCH=amd64 ~/go/bin/xcaddy build --with github.com/caddy-dns/cloudflare --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive --output caddy-with-cloudflare-dns-linux-amd64
            GOOS=linux GOARCH=arm64 ~/go/bin/xcaddy build --with github.com/caddy-dns/cloudflare --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive --output caddy-with-cloudflare-dns-linux-arm64
            upx --best caddy-with-cloudflare-dns-linux-amd64 caddy-with-cloudflare-dns-linux-arm64
            mkdir -p .github/workflows
            wget -qO .github/workflows/Backup.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/Backup.yml &> /dev/null
            git config --global init.defaultBranch main
            git init
            git add .
            git config user.name "hzdlive"
            git config user.email "3319136+hzdlive@users.noreply.github.com"
            git commit -m "caddy binary"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push origin main --force
